version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  nginx:
    build: https://github.com/jongonalv/erronkaKobaz.git
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
       - PUID=1000
       - PGID=1000
       - TZ=Etc/UTC
       - CLI_ARGS= #optional
    build: https://github.com/jongonalv/erronkaKobaz.git
    ports:
      - 8200:8200
    restart: unless-stopped
  