version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  nginx:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  duplicati:
    image: duplicati
    ports:
      - "8200:8200"
    volumes:
      - "/duplicati:/backup/home duplicati/duplicati"
  
  